# Generated by Django 5.1.6 on 2025-02-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
