# Generated by Django 5.1.6 on 2025-02-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_product_image_product_price_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/default-product.jpg', null=True, upload_to='product_images/'),
        ),
    ]
