# Generated by Django 5.1.6 on 2025-02-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_variant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='price',
        ),
    ]
