# Generated by Django 5.1.6 on 2025-02-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_variant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_images/'),
        ),
    ]
