# Generated by Django 5.1.6 on 2025-02-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_cart_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='authentication.address'),
            preserve_default=False,
        ),
    ]
