# Generated by Django 5.1.6 on 2025-02-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
