# Generated by Django 5.1.6 on 2025-03-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
