# Generated by Django 5.1.6 on 2025-03-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_remove_product_price_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='authentication.variant'),
            preserve_default=False,
        ),
    ]
