# Generated by Django 5.1.6 on 2025-03-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_alter_cart_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'variant')},
        ),
    ]
