# Generated by Django 5.1.6 on 2025-03-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'variant'], name='authenticat_user_id_a614fa_idx'),
        ),
    ]
